var json = require('./sample.json')
console.log(json.name)
console.log(json.profile)
console.log(json.tools)
console.log((json.tools).length)
console.log((json.tools[1]))
console.log(json.address.addressLine1)
console.log(json.address.addressLine2)
console.log(json.address.city)
console.log(json.demo[1].addressLine2)
console.log(json.test.homeAddress.address1)
console.log(json.test.homeAddress.address2)
console.log(json.demo[0].addressLine1)